/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2e2e2",
        "on-surface-variant": "#474832",
        "inverse-surface": "#303221",
        "inverse-primary": "#c0d100",
        "highlight-neon": "#EBFF00",
        primary: "#5b6400",
        "surface-bright": "#fbfbe2",
        "surface-container-highest": "#e4e4cc",
        secondary: "#5e5e5e",
        "on-background": "#1b1d0e",
        surface: "#fbfbe2",
        "on-primary-fixed": "#1a1d00",
        "surface-cream": "#F5F5DC",
        "on-tertiary-fixed": "#001f24",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-variant": "#e4e4cc",
        "tertiary-fixed-dim": "#aacdd2",
        "on-primary-fixed-variant": "#444b00",
        "secondary-fixed-dim": "#c6c6c6",
        error: "#ba1a1a",
        "surface-dim": "#dbdcc3",
        "tertiary-container": "#d6f9ff",
        "on-secondary-container": "#646464",
        "on-primary-container": "#6b7400",
        "outline-variant": "#c8c8ab",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f2f2d9",
        "primary-container": "#ebff00",
        "surface-container": "#efefd7",
        "primary-fixed-dim": "#c0d100",
        "on-primary": "#ffffff",
        "on-surface": "#1b1d0e",
        tertiary: "#436469",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        outline: "#77795f",
        "surface-tint": "#5b6400",
        "primary-fixed": "#dbee00",
        "on-tertiary-fixed-variant": "#2b4c51",
        "tertiary-fixed": "#c6e9ef",
        "surface-container-high": "#eaead1",
        "secondary-container": "#e2e2e2",
        background: "#fbfbe2",
        "structural-line": "#000000",
        "surface-container-low": "#f5f5dc",
        "on-secondary-fixed-variant": "#474747",
        "on-tertiary-container": "#537479",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1b1b1b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        none: "0px",
      },
      spacing: {
        "margin-mobile": "24px",
        unit: "4px",
        gutter: "0px",
        "margin-desktop": "48px",
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg-mobile": ["Space Grotesk"],
        "body-md": ["Inter"],
        "label-mono": ["JetBrains Mono"],
        "headline-md": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "display-lg-mobile": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      backgroundImage: {
        "grid-pattern":
          "linear-gradient(to right, rgba(0, 0, 0, 0.05) 1px, transparent 1px), linear-gradient(to bottom, rgba(0, 0, 0, 0.05) 1px, transparent 1px)",
      },
    },
  },
  plugins: [],
};
